name = input("ชื่ออะไร: ")
favorite_food = input("ชอบกินอะไร: ")
faovrite_movie = input("หนังที่ชอบ: ")
hobby = input("งานอดิเรก: ")
print(f"สวัสดีครับผมชื่อ {name} ชอบกิน {favorite_food} เวลาว่างชอบ {hobby} และหนังเรื่องโปรดคือ {faovrite_movie} ครับ")